replicaCount: 1

externalUrl: https://jollyroger.duckdns.org
serverName: jollyroger.duckdns.org

letsencrypt:
  image: josefreichardt/letsencrypt-kubernetes-secret:latest
  schedule: "0 2 1 * *"
  domains: jollyroger.duckdns.org
  email: reichardt.josef@gmail.com

mariadb:
  image: mariadb:latest
  user: nextcloud
  database: nextcloud
  # password: Geheim123! # pass via --set
  # initialRootPassword: Geheim123! # pass via --set

nextcloud:
  image: nextcloud:latest
  # initialAdminPassword: Geheim123! # pass via --set
  adminUser: admin

nginx:
  image: nginx:latest

backup:
  nextcloud:
    image: mariadb:latest
    schedule: "0 1 * * 0"
  nas:
    image: debian:buster
    files:
      schedule: "30 1 * * 0"
    fotos:
      schedule: "0 3 1 1,7 *"
