replicaCount: 1

externalUrl: https://jollyroger.duckdns.org
serverName: jollyroger.duckdns.org

letsencrypt:
  email: reichardt.josef@gmail.com

mariadb:
  image: mariadb:latest
  user: nextcloud
  database: nextcloud
  # password: Geheim123! # pass via --set
  # initialRootPassword: Geheim123! # pass via --set

nextcloud:
  image: nextcloud:latest
  # initialAdminPassword: Geheim123! # pass via --set
  adminUser: admin

redis:
  image: redis:latest
  # password: "Geheim123!"

nginx:
  image: nginx:latest

backup:
  nextcloud:
    image: mariadb:latest
    schedule: "0 1 * * 0"

plex:
  image: plexinc/pms-docker
  # claim: claim-1234567890

deconz:
  vncEnabled: "0"

n8n:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: jollyroger-letsencrypt-issuer
    hosts:
      - host: n8n.jollyroger.duckdns.org
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: n8n-tls
        hosts:
          - n8n.jollyroger.duckdns.org
  main:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  worker:
    mode: queue
    count: 3
    concurrency: 10
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 2Gi
