replicaCount: 1

externalUrl: https://jollyroger.duckdns.org
serverName: jollyroger.duckdns.org

letsencrypt:
  email: reichardt.josef@gmail.com

mariadb:
  image: mariadb:latest
  user: nextcloud
  database: nextcloud
  # password: Geheim123! # pass via --set
  # initialRootPassword: Geheim123! # pass via --set

nextcloud:
  image: nextcloud:latest
  # initialAdminPassword: Geheim123! # pass via --set
  adminUser: admin

redis:
  image: redis:latest
  # password: "Geheim123!"

nginx:
  image: nginx:latest

backup:
  nextcloud:
    image: mariadb:latest
    schedule: "0 1 * * 0"

plex:
  image: plexinc/pms-docker
  # claim: claim-1234567890

deconz:
  vncEnabled: "0"

n8n:
  enabled: false
  # see https://github.com/8gears/n8n-helm-chart/blob/main/charts/n8n/values.yaml
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: public
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: jollyroger-letsencrypt-issuer
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "1g"
      nginx.org/client-max-body-size: "1g"
    # define a custom ingress class Name, like "traefik" or "nginx"
    className: ""
    hosts:
      - host: n8n.jollyroger.duckdns.org
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - n8n.jollyroger.duckdns.org
        secretName: n8n-jollyroger-duckdns-org-cert
