replicaCount: 1

externalUrl: https://jollyroger.duckdns.org
serverName: jollyroger.duckdns.org

letsencrypt:
  email: reichardt.josef@gmail.com

mariadb:
  image: mariadb:latest
  user: nextcloud
  database: nextcloud
  # password: Geheim123! # pass via --set
  # initialRootPassword: Geheim123! # pass via --set

nextcloud:
  image: nextcloud:latest
  # initialAdminPassword: Geheim123! # pass via --set
  adminUser: admin

nginx:
  image: nginx:latest

backup:
  nextcloud:
    image: mariadb:latest
    schedule: "0 1 * * 0"

plex:
  image: plexinc/pms-docker
  # claim: claim-1234567890

deconz:
  vncEnabled: "0"
