apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: jollyroger
version: 0.1.0
dependencies:
  - name: n8n
    version: "2.0.1"
    repository: "oci://8gears.container-registry.com/library/n8n"
    condition: n8n.enabled
