replicaCount: 1

externalUrl: https://jollyroger.duckdns.org
serverName: jollyroger.duckdns.org

letsencrypt:
  image: josefreichardt/letsencrypt-kubernetes-secret:latest
  schedule: "0 2 1 * *"
  domains: jollyroger.duckdns.org
  email: reichardt.josef@gmail.com

mariadb:
  image: mariadb:latest
  user: nextcloud
  database: nextcloud
  # password: Geheim123! # pass via --set
  # initialRootPassword: Geheim123! # pass via --set

nextcloud:
  image: nextcloud:latest
  # initialAdminPassword: Geheim123! # pass via --set
  adminUser: admin

nginx:
  image: nginx:latest

backup:
  image: mariadb:latest
  schedule: "0 3 * * 0"
  # targetSshHost: nas # pass via --set
  # targetSshPath: backups # pass via --set
  # targetSshUser: admin # pass via --set
  # targetSshPassword: Geheim123! # pass via --set
