apiVersion: v1
kind: Secret
metadata:
  name: backup-secrets
type: Opaque
data:
  SSH_TARGET_HOST: "{{ .Values.backup.targetSsh.host | required "Value for backup.targetSsh.host is required!" | b64enc }}"
  SSH_TARGET_USER: "{{ .Values.backup.targetSsh.user | required "Value for backup.targetSsh.password is required!" | b64enc }}"
  SSH_TARGET_PASSWORD: "{{ .Values.backup.targetSsh.password | required "Value for backup.targetSsh.password is required!" | b64enc }}"
  SSH_TARGET_PATH: "{{ .Values.backup.targetSsh.path | required "Value for backup.targetSsh.path is required!" | b64enc }}"
