apiVersion: v1
kind: Secret
metadata:
  name: backup-secrets
type: Opaque
data:
  SSH_TARGET_HOST: "{{ .Values.backup.targetSshHost | required "Value for backup.targetSshHost is required!" | b64enc }}"
  SSH_TARGET_USER: "{{ .Values.backup.targetSshUser | required "Value for backup.targetSshPassword is required!" | b64enc }}"
  SSH_TARGET_PASSWORD: "{{ .Values.backup.targetSshPassword | required "Value for backup.targetSshPassword is required!" | b64enc }}"
  SSH_TARGET_PATH: "{{ .Values.backup.targetSshPath | required "Value for backup.targetSshPath is required!" | b64enc }}"
