apiVersion: v1
kind: Service
metadata:
  name: deconz
spec:
  selector:
    app: deconz
  ports:
    - name: http
      protocol: TCP
      port: 30080
      targetPort: 30080
    - name: https
      protocol: TCP
      port: 30443
      targetPort: 30443
