apiVersion: v1
kind: Service
metadata:
  name: deconz
spec:
  type: NodePort
  selector:
    app: deconz
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 9000
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
      nodePort: 9443
