apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: true
    cert-manager.io/cluster-issuer: jollyroger-letsencrypt-issuer
spec:
  tls:
    - secretName: jollyroger-letsencryp-secret
      hosts:
        - jollyroger.duckdns.org
    - host: jollyroger.duckdns.org
      http:
        paths:
          - backend:
            service:
              name: nextcloud
              port:
                number: 80
            path: /
            pathType: Exact
