apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: jollyroger-letsencrypt-issuer
spec:
  acme:
    email: {{ .Values.letsencrypt.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: jollyroger-letsencrypt-secret
    solvers:
      - http01:
          ingress:
            class: nginx
