apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: letsencrypt-job
  labels:
    app: letsencrypt
spec:
  schedule: {{ .Values.letsencrypt.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: letsencrypt
          labels:
            app: letsencrypt
        spec:
          containers:
          - image: {{ .Values.letsencrypt.image }}
            name: letsencrypt
            imagePullPolicy: Always
            ports:
            - name: letsencrypt
              containerPort: 80
            env:
            - name: DOMAINS
              value: {{ .Values.letsencrypt.domains }}
            - name: EMAIL
              value: {{ .Values.letsencrypt.email }}
            - name: SECRET
              value: letsencrypt-certs
          restartPolicy: Never
