apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  MYSQL_PASSWORD: "{{ .Values.mariadb.password | required "Value for mariadb.password is required!" | b64enc }}"
  MYSQL_ROOT_PASSWORD: "{{ .Values.mariadb.initialRootPassword | required "Value for mariadb.initialRootPassword is required!" | b64enc }}"
