apiVersion: v1
kind: Secret
metadata:
  name: nas-secrets
type: Opaque
data:
  NAS_SSH_HOST: "{{ .Values.backup.nas.ssh.host | required "Value for backup.nas.ssh.host is required!" | b64enc }}"
  NAS_SSH_USER: "{{ .Values.backup.nas.ssh.user | required "Value for backup.nas.ssh.user is required!" | b64enc }}"
  NAS_SSH_PASSWORD: "{{ .Values.backup.nas.ssh.password | required "Value for backup.nas.ssh.password is required!" | b64enc }}"
  NAS_FILES_PATH: "{{ .Values.backup.nas.files.path | required "Value for backup.nas.files.path is required!" | b64enc }}"
  NAS_FOTOS_PATH: "{{ .Values.backup.nas.fotos.path | required "Value for backup.nas.fotos.path is required!" | b64enc }}"
