apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
data:
  custom-entrypoint.sh: |
    #!/bin/bash

    apt-get update && apt-get install -y \
      php-imagick \
      && rm -rf /var/lib/apt/lists/*

    /entrypoint.sh
  crontab: |
    */5 * * * * www-data php -f /var/www/html/cron.php
    0   0 * * 0 www-data php -f /var/www/html/occ fulltextsearch:index
