apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-backup-config
data:
  run_backup.sh: |
    #!/bin/bash
    echo "### Install sshpass"
    apt-get update && apt-get install -y sshpass
    export BACKUP_FILE_PREFIX="jollyroger_nextcloud_backup_"
    export BACKUP_FILE="/tmp/${BACKUP_FILE_PREFIX}$(date '+%Y-%m-%d_%H-%M-%S').tar.gz"
    echo "### Backup filename will be ${BACKUP_FILE}"
    echo "### Create nextcloud database backup ..."
    mysqldump -h mariadb -u root -p${MYSQL_ROOT_PASSWORD} --databases nextcloud > /nextcloud.sql
    echo "### Compress backup ..."
    cd /
    tar -czvf ${BACKUP_FILE} nextcloud-data nextcloud.sql
    echo "### Upload backup file ..."
    sshpass -p "${SSH_TARGET_PASSWORD}" scp -o StrictHostKeyChecking=no -r ${BACKUP_FILE} ${SSH_TARGET_USER}@${SSH_TARGET_HOST}:${SSH_TARGET_PATH}
    echo "### Cleanup old backups ..."
    OUTDATED_FILES=$(sshpass -p "${SSH_TARGET_PASSWORD}" \
      ssh -o StrictHostKeyChecking=no ${SSH_TARGET_USER}@${SSH_TARGET_HOST} \
      find ${SSH_TARGET_PATH} -name "${BACKUP_FILE_PREFIX}*.tar.gz" -follow -mtime +22 -type f -print)
    echo $OUTDATED_FILES
    echo $OUTDATED_FILES | xargs -0 sshpass -p "${SSH_TARGET_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SSH_TARGET_USER}@${SSH_TARGET_HOST} rm -f
    echo "Finished!"
