apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
data:
  custom-entrypoint.sh: |
    #!/bin/bash

    set -e

    apt-get update \
      && apt-get install -y libmagickwand-dev --no-install-recommends \
      && apt-get install -y \
        sudo \
        cron \
      && pecl install imagick && docker-php-ext-enable imagick \
      && rm -rf /var/lib/apt/lists/*

    crontab -u www-data /etc/cron.d/nextcloud
    service cron start

    /entrypoint.sh apache2-foreground
  crontab: |
    */5 * * * * PHP_MEMORY_LIMIT=512M php -f /var/www/html/cron.php
    0   0 * * 0 PHP_MEMORY_LIMIT=512M php -f /var/www/html/occ fulltextsearch:index
