apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nextcloud-backup-job
  labels:
    app: nextcloud-backup-job
spec:
  schedule: {{ .Values.backup.nextcloud.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: nextcloud-backup-job
          labels:
            app: nextcloud-backup-job
        spec:
          containers:
            - image: {{ .Values.backup.nextcloud.image }}
              name: nextcloud-backup-job
              imagePullPolicy: Always
              command: ["/nextcloud-backup-config/run_backup.sh"]
              env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mariadb-secrets
                      key: MYSQL_ROOT_PASSWORD
                - name: SSH_TARGET_HOST
                  valueFrom:
                    secretKeyRef:
                      name: backup-secrets
                      key: SSH_TARGET_HOST
                - name: SSH_TARGET_PATH
                  valueFrom:
                    secretKeyRef:
                      name: backup-secrets
                      key: SSH_TARGET_PATH
                - name: SSH_TARGET_USER
                  valueFrom:
                    secretKeyRef:
                      name: backup-secrets
                      key: SSH_TARGET_USER
                - name: SSH_TARGET_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: backup-secrets
                      key: SSH_TARGET_PASSWORD
              volumeMounts:
                - name: nextcloud-data
                  mountPath: /nextcloud-data
                - name: nextcloud-backup-config
                  mountPath: /nextcloud-backup-config/run_backup.sh
                  subPath: run_backup.sh
          restartPolicy: Never
          volumes:
            - name: nextcloud-backup-config
              configMap:
                name: nextcloud-backup-config
                defaultMode: 0777
            - name: nextcloud-data
              hostPath:
                path: "/data/nextcloud"
