apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-cronjob
  labels:
    app: nextcloud
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: nextcloud-cronjob
          labels:
            app: nextcloud
        spec:
          securityContext:
            runAsUser: 33
          containers:
            - image: {{ .Values.nextcloud.image }}
              name: nextcloud-cronjob
              imagePullPolicy: Always
              command: ["php", "-f", "/var/www/html/cron.php"]
              env:
                - name: TZ
                  value: Europe/Berlin
                - name: DEBUG
                  value: "false"
                - name: PHP_MEMORY_LIMIT
                  value: "512M"
                - name: NEXTCLOUD_URL
                  value: {{ .Values.externalUrl }}
                - name: NEXTCLOUD_TRUSTED_DOMAINS
                  value: {{ .Values.serverName }}
                - name: NEXTCLOUD_ADMIN_USER
                  value: {{ .Values.nextcloud.adminUser }}
                - name: NEXTCLOUD_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: nextcloud-secrets
                      key: NEXTCLOUD_ADMIN_PASSWORD
                - name: NEXTCLOUD_UPLOAD_MAX_FILESIZE
                  value: 16G
                - name: NEXTCLOUD_MAX_FILE_UPLOADS
                  value: "200"
                - name: MYSQL_DATABASE
                  value: {{ .Values.mariadb.database }}
                - name: MYSQL_HOST
                  value: mariadb
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mariadb-secrets
                      key: MYSQL_PASSWORD
                - name: MYSQL_USER
                  value: {{ .Values.mariadb.user }}
              volumeMounts:
                - name: html
                  mountPath: /var/www/html
          restartPolicy: Never
          volumes:
            - name: html
              hostPath:
                path: "/data/nextcloud"
