apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
type: Opaque
data:
  NEXTCLOUD_ADMIN_PASSWORD: "{{ .Values.nextcloud.initialAdminPassword | required "Value for nextcloud.initialAdminPassword is required!" | b64enc }}"
