apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream letsencrypt {
      server letsencrypt:80 max_fails=0 fail_timeout=1s;
    }

    server {
      listen 80;
      listen [::]:80;
      server_name {{ .Values.serverName }};

      location ^~ /.well-known/acme-challenge/ {
        proxy_pass http://letsencrypt;
      }

      location / {
        return 301 https://$server_name$request_uri;
      }
    }

    server {
      listen 443 ssl;
      access_log  /var/log/nginx/access.log;

      server_name {{ .Values.serverName }};
      ssl_certificate /etc/nginx/ssl/fullchain.pem;
      ssl_certificate_key /etc/nginx/ssl/privkey.pem;

      proxy_set_header Referrer-Policy "no-referrer";
      proxy_set_header X-Content-Type-Options "nosniff";
      proxy_set_header X-Download-Options "noopen";
      proxy_set_header X-Frame-Options "SAMEORIGIN";
      proxy_set_header X-Permitted-Cross-Domain-Policies "none";
      proxy_set_header X-Robots-Tag "none";
      proxy_set_header X-XSS-Protection "1; mode=block";
      proxy_set_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";

      # set max upload size
      client_max_body_size 4G;

      # Enable gzip but do not remove ETag headers
      gzip on;
      gzip_vary on;
      gzip_comp_level 4;
      gzip_min_length 256;
      gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
      gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;

      location = /.well-known/carddav {
        return 301 $scheme://$host:$server_port/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 $scheme://$host:$server_port/remote.php/dav;
      }

      location / {
        proxy_pass http://nextcloud;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_buffering off;
        proxy_request_buffering off;
      }
    }

