apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openhab
  name: openhab
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openhab
  template:
    metadata:
      labels:
        app: openhab
    spec:
      containers:
      - name: openhab
        image: openhab/openhab
        env:
          - name: CRYPTO_POLICY
            value: "unlimited"
          - name: EXTRA_JAVA_OPTS
            value: "-Duser.timezone=Europe/Berlin"
          - name: OPENHAB_HTTP_PORT
            value: "8080"
          - name: OPENHAB_HTTPS_PORT
            value: "8443"
        ports:
        - containerPort: 8080
        - containerPort: 8443
        volumeMounts:
        - mountPath: /openhab/addons
          name: openhab-addons
        - mountPath: /openhab/conf
          name: openhab-conf
        - mountPath: /openhab/userdata
          name: openhab-userdata
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /etc/timezone
          name: timezone
      volumes:
      - name: openhab-addons
        hostPath:
          path: /data/openhab/addons
      - name: openhab-conf
        hostPath:
          path: /data/openhab/conf
      - name: openhab-userdata
        hostPath:
          path: /data/openhab/userdata
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: timezone
        hostPath:
          path: /etc/timezone
