---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: islademuerta-filme
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: islademuerta
    path: "/Multimedia/test"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: islademuerta-filme
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: islademuerta-filme
---
