apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plex
  name: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: {{ .Values.plex.image }}
          env:
            - name: "TZ"
              value: "Europe/Berlin"
            - name: "PLEX_CLAIM"
              value: {{ .Values.plex.claim }}
          ports:
            - name: http
              containerPort: 32400
              hostPort: 32400
              protocol: TCP
            - containerPort: 3005
              hostPort: 3005
              protocol: TCP
            - containerPort: 8324
              hostPort: 8324
              protocol: TCP
            - containerPort: 32469
              hostPort: 32469
              protocol: TCP
            - containerPort: 1900
              hostPort: 1900
              protocol: UDP
            - containerPort: 32410
              hostPort: 32410
              protocol: UDP
            - containerPort: 32412
              hostPort: 32412
              protocol: UDP
            - containerPort: 32413
              hostPort: 32413
              protocol: UDP
            - containerPort: 32414
              hostPort: 32414
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
            - name: data
              mountPath: /data
      volumes:
        - name: config
          hostPath:
            path: "/data/plex/config"
        - name: transcode
          hostPath:
            path: "/data/plex/transcode"
        - name: data
          hostPath:
            path: "/mnt/plex-data"
